export const initialGroups = [
  {
    id: "group-access",
    name: "Access",
    repeat: {
      enabled: false,
      mode: "count",
      count: 1,
      useData: true,
    },
    steps: [
      {
        id: "access-step-1",
        title: "Buka Halaman Login",
        description: "Arahkan browser ke https://contoh.app/login",
        type: "Navigate",
        scopeSelector: "",
        value: "",
        label: "",
        timeoutMs: "5000",
        waitMs: "",
        url: "https://contoh.app/login",
      },
      {
        id: "access-step-2",
        title: "Input Username",
        description: "Masukkan username",
        type: "Input",
        scopeSelector: "",
        inputKind: "text",
        dateFormat: "",
        value: "root",
        label: "Username",
        timeoutMs: "5000",
        waitMs: "",
        url: "",
      },
      {
        id: "access-step-3",
        title: "Input Password",
        description: "Masukkan password",
        type: "Input",
        scopeSelector: "",
        inputKind: "text",
        dateFormat: "",
        value: "1234",
        label: "Password",
        timeoutMs: "5000",
        waitMs: "",
        url: "",
      },
      {
        id: "access-step-4",
        title: "Klik Sign In",
        description: "Klik tombol sign in",
        type: "Click",
        scopeSelector: "",
        value: "",
        label: "Sign in",
        timeoutMs: "5000",
        waitMs: "",
        url: "",
      },
    ],
  },
  {
    id: "group-after-login",
    name: "After Login",
    repeat: {
      enabled: false,
      mode: "count",
      count: 1,
      useData: true,
    },
    steps: [
      {
        id: "after-step-1",
        title: "Validasi Dashboard",
        description: "Pastikan dashboard muncul tanpa error",
        type: "Wait",
        scopeSelector: "",
        value: "",
        label: "",
        timeoutMs: "5000",
        waitMs: "1000",
        url: "",
      },
    ],
  },
  {
    id: "group-signout",
    name: "Sign Out Flow",
    repeat: {
      enabled: false,
      mode: "count",
      count: 1,
      useData: true,
    },
    steps: [
      {
        id: "signout-step-1",
        title: "Klik Sign Out",
        description: "Keluar dari aplikasi",
        type: "Click",
        scopeSelector: "",
        value: "",
        label: "Sign out",
        timeoutMs: "5000",
        waitMs: "",
        url: "",
      },
    ],
  },
];
