export const initialGroups = [
  {
    id: "group-access",
    name: "Access",
    steps: [
      {
        id: "access-step-1",
        title: "Buka Halaman Login",
        description: "Arahkan browser ke https://contoh.app/login",
        type: "Navigate",
        selector: "",
        value: "",
        label: "",
        timeoutMs: "5000",
        waitMs: "",
        url: "https://contoh.app/login",
      },
      {
        id: "access-step-2",
        title: "Input Username",
        description: "Masukkan username",
        type: "Input",
        selector: "",
        targetType: "label",
        value: "root",
        label: "Username",
        timeoutMs: "5000",
        waitMs: "",
        url: "",
      },
      {
        id: "access-step-3",
        title: "Input Password",
        description: "Masukkan password",
        type: "Input",
        selector: "",
        targetType: "label",
        value: "1234",
        label: "Password",
        timeoutMs: "5000",
        waitMs: "",
        url: "",
      },
      {
        id: "access-step-4",
        title: "Klik Sign In",
        description: "Klik tombol sign in",
        type: "Click",
        selector: "",
        targetType: "label",
        value: "",
        label: "Sign in",
        timeoutMs: "5000",
        waitMs: "",
        url: "",
      },
    ],
  },
  {
    id: "group-after-login",
    name: "After Login",
    steps: [
      {
        id: "after-step-1",
        title: "Validasi Dashboard",
        description: "Pastikan dashboard muncul tanpa error",
        type: "Wait",
        selector: ".dashboard",
        value: "",
        label: "",
        timeoutMs: "5000",
        waitMs: "1000",
        url: "",
      },
    ],
  },
  {
    id: "group-checkout",
    name: "Checkout Flow",
    steps: [
      {
        id: "checkout-step-1",
        title: "Buka Keranjang",
        description: "Masuk ke halaman keranjang",
        type: "Click",
        selector: "#cart",
        targetType: "selector",
        value: "",
        label: "",
        timeoutMs: "5000",
        waitMs: "",
        url: "",
      },
    ],
  },
];
