export const initialGroups = [
  {
    id: "group-access",
    name: "Access",
    steps: [
      {
        id: "access-step-1",
        title: "Buka Halaman Login",
        description: "Arahkan browser ke https://contoh.app/login",
        type: "Navigate",
        selector: "",
        value: "",
        label: "",
        waitMs: "",
        url: "https://contoh.app/login",
      },
      {
        id: "access-step-2",
        title: "Isi Kredensial",
        description: "Masukkan email dan password pengguna",
        type: "Input",
        selector: "#username",
        value: "",
        label: "",
        waitMs: "",
        url: "",
      },
      {
        id: "access-step-3",
        title: "Klik Masuk",
        description: "Tekan tombol Masuk dan tunggu halaman berikutnya",
        type: "Click",
        selector: "#submit",
        value: "",
        label: "",
        waitMs: "",
        url: "",
      },
    ],
  },
  {
    id: "group-after-login",
    name: "After Login",
    steps: [
      {
        id: "after-step-1",
        title: "Validasi Dashboard",
        description: "Pastikan dashboard muncul tanpa error",
        type: "Read Text",
        selector: ".dashboard",
        value: "",
        label: "Status Dashboard",
        waitMs: "",
        url: "",
      },
    ],
  },
  {
    id: "group-checkout",
    name: "Checkout Flow",
    steps: [
      {
        id: "checkout-step-1",
        title: "Buka Keranjang",
        description: "Masuk ke halaman keranjang",
        type: "Click",
        selector: "#cart",
        value: "",
        label: "",
        waitMs: "",
        url: "",
      },
    ],
  },
];
